### ISSUE TITLE
Node-based Test doesn't include Mocha

### ISSUE THREAD

**Issue by tmarrs** [phillipalexander/generator-test#7]
Mocha was missing when I created a project using `yo test` with the Node option. I fixed this by doing `npm install --save mocha` from the command line. Other than that, this generator works well.

But this is a workaround.

Please add Mocha as a dependency to the Node flavor of this generator so that Mocha is automatically installed when the generator does its `npm install`.

**Comment by phillipalexander** [comment]
Thanks for the bug report! The issue was fixed in https://github.com/phillipalexander/generator-test/commit/ec09981035d3aaaed8fc7d2f238454fcd5246e4e, but the fix hadn't been published to npm. I just published the latest version so you're good to go.
